/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

import Administracion.*;
import static Contabilidad.menues.nombreBase;
import Empresas.coneccionEmp;
import Empresas.menuEmpresas;
import java.net.InetAddress;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;


/**
 *
 * @author jonathan
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        
        setLocationRelativeTo(null);
       
        coneccionBD.BD=nombreEmpresa;
         metodos=new metodos_login();
         
         backup.nomBD=nombreEmpresa;
         
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Acceso de Usuario");

        jLabel2.setText("Nombre de Acceso");

        jLabel3.setText("Password");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("Entrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(171, 171, 171))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(147, 147, 147))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 131, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(125, 125, 125))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(162, 162, 162))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        metodos_login miLog=new metodos_login();
        
        boolean esta=miLog.verificar_usuario(jTextField1.getText(), jPasswordField1.getText());
        
        if(esta==true){
             ventana_supervisor vs=new ventana_supervisor();

                              nombreUsuario=jTextField1.getText();

                              vs.jTextField1.setText(nombreUsuario);

                             try{
                              InetAddress address = InetAddress.getLocalHost();

                             //   abrir.jTextField2.setText(address.getHostAddress());
                              vs.jTextField2.setText(address.getHostName());
                              }catch(Exception e){

                              }
            if (nombreEmpresa.equals("empresas")){
               
                
                
                ventana_supervisor.jButton2.setVisible(false);
                ventana_supervisor.jButton3.setVisible(false);
                ventana_supervisor.jButton4.setVisible(false);
                ventana_supervisor.jButton8.setVisible(false);
                ventana_supervisor.jButton9.setVisible(false);
                ventana_supervisor.jButton10.setVisible(false);
            }else{
                
                ventana_supervisor.jButton7.setVisible(false);
                   

                            coneccionBD.BD=nombreEmpresa;
                            coneccionBD conn =new coneccionBD();
                           // ResultSet ult_imp= conn.listar("ultima_impresion");
                       
            
            
            
                            coneccionEmp conexionEmp=new coneccionEmp();

                             ResultSet result=conexionEmp.listar("misempresas");

                             try{

                                boolean encontre=false; 
                                while(result.next() && encontre==false){

                                    if(result.getString("id_empresa").equals(nombreEmpresa)){
                                        encontre=true;
                                        fecha_apertura=result.getString("fecha_apertura");
                                        System.out.println(fecha_apertura);
                                        fecha_cierre=result.getString("fecha_cierre");
                                        razon_social=result.getString("razon_social");
                                        situacion_iva=result.getString("situacion_iva");
                                        cuit=result.getString("cuit");
                                        actividad=result.getString("actividad");
                                        empresa=result.getString("nombre");
                                        domicilio=result.getString("domicilio");
                                        localidad=result.getString("localidad");
                                    }

                                }



                             }catch(Exception e){

                             }

                             

                             idperfil=metodos.dameClavePerfil(jTextField1.getText() ,jPasswordField1.getText());
                            String tipo=metodos.dameTipoPerfil(idperfil);

                            switch(tipo){

                                case "Auditor":ventana_supervisor.jButton2.setVisible(false);
                                               ventana_supervisor.jButton3.setVisible(false);
                                               ventana_supervisor.jButton5.setVisible(false);
                                               ventana_supervisor.jButton6.setVisible(false);
                                               ventana_supervisor.jButton7.setVisible(false);
                                               ventana_supervisor.jButton8.setVisible(false);
                                               ventana_supervisor.jButton9.setVisible(false);
                                               ventana_supervisor.jButton10.setVisible(false);
                                                  break;
                                case "Administrador":   // ventana_supervisor.jButton6.setVisible(false);
                                                        // ventana_supervisor.jButton7.setVisible(false);

                                                                 break;
                                 case "Supervisor":     
                                                        ventana_supervisor.jButton5.setVisible(false);
                                                        ventana_supervisor.jButton6.setVisible(false);
                                                    
                                                     break;

                            }
            }
            
            
            vs.setVisible(true);
            
            this.dispose();
            
        }else{
            JOptionPane.showMessageDialog(null, "No Perteneces a esta Empresa");
            menuEmpresas emp=new menuEmpresas();
            emp.setVisible(true);
            this.dispose();
        }
   
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }
    
   
    
public metodos_login metodos;
public static int idperfil;
public static String nombreEmpresa;
public static String empresa;
public static String domicilio;
public static String localidad;
public static String nombreUsuario;
public static String fecha_apertura;
public static String fecha_cierre;
public static String fecha_ult_diario;
public static String razon_social;
public static String situacion_iva;
public static String cuit;
public static String actividad;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
