/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Administracion;

/**
 *
 * @author jonathan
 */
import BackupEmpresa.MyFileReader;
import BackupEmpresa.funcionesBackup;
import Empresas.*;
import java.io.IOException;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class backupEmpresas extends javax.swing.JPanel {
    
    

    /**
     * Creates new form backupEmpresas
     */
    public backupEmpresas() {
        initComponents();
        url= "jdbc:mysql://localhost/";
        log="root";
        pass="";
        
        misFunciones=new funcionesBackup();
        
        jFileChooser1.setVisible(false);
        
        conect=new coneccionEmp();
         
         ResultSet r=conect.listar("misempresas");
         
        jComboBox1.removeAllItems();
        
        jComboBox1.setSelectedItem(null);
         
         try{
             
             while(r.next()){
                 
                 jComboBox1.addItem(r.getString("nombre"));
                 
             }
             
         }catch(Exception e){
             
         }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnBackup = new javax.swing.JButton();
        btnRestaurar = new javax.swing.JButton();
        jFileChooser1 = new javax.swing.JFileChooser();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Elija una Empresa");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        btnBackup.setText("Guardar");
        btnBackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackupActionPerformed(evt);
            }
        });

        btnRestaurar.setText("Restaurar");
        btnRestaurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaurarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(145, 145, 145)
                            .addComponent(btnBackup)
                            .addGap(39, 39, 39)
                            .addComponent(btnRestaurar))))
                .addContainerGap(628, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBackup)
                    .addComponent(btnRestaurar))
                .addGap(64, 64, 64)
                .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(161, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackupActionPerformed
      bd=dameId();

        misFunciones.HacerBackup(jFileChooser1, bd);
    }//GEN-LAST:event_btnBackupActionPerformed

    private void btnRestaurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaurarActionPerformed
       bd=dameId();

        MyFileReader miLectura=new MyFileReader();
        
        String miArchivo=misFunciones.dameArchivo();
        String nombre_bd=null;
        
        try {
            nombre_bd=miLectura.leer(miArchivo);
        } catch (IOException ex) {
            Logger.getLogger(backupEmpresas.class.getName()).log(Level.SEVERE, null, ex);
        }
        
         if(bd.equals(nombre_bd)){
            
            try{
             Connection coneccion=DriverManager.getConnection(url, log, pass);
             String[]miArreglo=misFunciones.dameComando(miArchivo);
             misFunciones.RestaurarBackup(coneccion, miArreglo, bd);
            }catch(Exception e){}
        }else{
            JOptionPane.showMessageDialog(null, "no tenes permiso");
        }

    }//GEN-LAST:event_btnRestaurarActionPerformed

    
    
   
    
    public String dameId(){
        
       ResultSet datos=conect.listar("misempresas");
       String id="";
       String nom=jComboBox1.getSelectedItem().toString();
       boolean encontre=false;
        try{
             
             while(datos.next() && encontre==false){
                 
                 if(datos.getString("nombre").equals(nom)){
                     
                     encontre=true;
                     id=datos.getString("id_empresa");
                     
                 }
                 
             }
             
         }catch(Exception e){
             
         }
        
        return id;
    }
    private funcionesBackup misFunciones;
    private String bd,url,log,pass;
    private coneccionEmp conect;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackup;
    private javax.swing.JButton btnRestaurar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
