/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Administracion;


import Reporte.*;

import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.io.File;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.table.*;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author jonathan
 */
public class registrosAuditoria extends javax.swing.JPanel{

    /**
     * Creates new form misRegistros
     */
    public registrosAuditoria() {
        initComponents();
        
         metodos=new metodosTabla();
        
         mod=metodos.dameModelo("auditorArticulo");
        
        jTable1.setModel(mod);
        
        mod2=metodos.dameModelo("auditorPago");
        
        jTable2.setModel(mod2);
        
        int t1=jTable1.getRowCount();
        int t2=jTable2.getRowCount();
        
        if(t1>0){
         insertaCombo(jTable1,jComboBox1);   
         
         insertaCombo(jTable1,jComboBox2);
         
         itemSeleccionado seleccion=new itemSeleccionado();
         jComboBox1.addItemListener(seleccion);
         
         itemHasta sel=new itemHasta();
         jComboBox2.addItemListener(sel);
        }
        
        if(t2>0){ 
         insertaCombo(jTable2,jComboBox3);   
         
         insertaCombo(jTable2,jComboBox4);
         
           itemPago1 i1=new itemPago1();
         jComboBox3.addItemListener(i1);
         
         itemPago2 i2=new itemPago2();
         jComboBox4.addItemListener(i2);
        
        }
         //-------------------------------------------------
       
         
       
    }
    
    public void insertaCombo(JTable tabla,JComboBox combo){
        
        combo.removeAllItems();
        
        combo.addItem("Todos");
        
         anterior=tabla.getValueAt(0, 3).toString();
        
        combo.addItem(anterior);
        
        for(int i=1;i<tabla.getRowCount();i++){
            
            siguiente=tabla.getValueAt(i, 3).toString();
            
            if(anterior.equals(siguiente)==false){
                
               combo.addItem(siguiente);
               
               anterior=siguiente;
                
            }
            
        }
      //  combo.setSelectedItem(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        generar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        generar1 = new javax.swing.JButton();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(204, 204, 204));

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 437));

        jTable1 = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int ColIndex){
                return false;
            }
        };
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.getTableHeader().setResizingAllowed(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        jPanel3.setBackground(new java.awt.Color(153, 255, 153));

        jLabel2.setText("Fecha Desde");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Fecha Hasta");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        generar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/save.png"))); // NOI18N
        generar.setText("Guardar");
        generar.setBorder(null);
        generar.setBorderPainted(false);
        generar.setContentAreaFilled(false);
        generar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        generar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        generar.setIconTextGap(2);
        generar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        generar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        generar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox1, 0, 142, Short.MAX_VALUE)
                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(110, 110, 110)
                .addComponent(generar)
                .addContainerGap(280, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(generar))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(172, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Auditoria Articulos", jPanel1);

        jPanel2.setPreferredSize(new java.awt.Dimension(1000, 437));

        jTable2 = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int ColIndex){
                return false;
            }
        };
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.getTableHeader().setResizingAllowed(false);
        jTable2.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable2);

        jPanel4.setBackground(new java.awt.Color(153, 255, 153));

        jLabel5.setText("Fecha Desde");

        jLabel6.setText("Fecha Hasta");

        generar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/save.png"))); // NOI18N
        generar1.setText("Guardar");
        generar1.setBorder(null);
        generar1.setBorderPainted(false);
        generar1.setContentAreaFilled(false);
        generar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        generar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        generar1.setIconTextGap(2);
        generar1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        generar1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        generar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generar1ActionPerformed(evt);
            }
        });

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(128, 128, 128)
                .addComponent(generar1)
                .addContainerGap(224, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(generar1))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 975, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Auditoria Pago", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void generarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarActionPerformed
        // TODO add your handling code here:

         ArrayList lista=new ArrayList();
        
        for(int i=0;i<jTable1.getRowCount();i++){
            
            ListaAuditorArticulo misArticulos=new ListaAuditorArticulo(jTable1.getValueAt(i, 6).toString(),jTable1.getValueAt(i, 7).toString(),jTable1.getValueAt(i, 8).toString(),jTable1.getValueAt(i, 9).toString(),jTable1.getValueAt(i, 10).toString());
            
            lista.add(misArticulos);
            
        }
        
        try {
            File fichero = new File("src/Reporte/ReporteAuditorArticulo.jasper");
            String ruta=fichero.getAbsolutePath();
            String barra=File.separator;
            String dobleBarra=File.separator+File.separator;
            String rutaNueva=ruta.replace(barra,dobleBarra);
                                                                          
            JasperReport reporte=(JasperReport) JRLoader.loadObjectFromFile(rutaNueva);
            
            Map parametro = new HashMap();
            //
            parametro.put("usuario", ventana_supervisor.jTextField1.getText());
            parametro.put("desde", jComboBox1.getSelectedItem());
            parametro.put("hasta", jComboBox2.getSelectedItem());
            
            JasperPrint jprint=JasperFillManager.fillReport(reporte,parametro,new JRBeanCollectionDataSource(lista));
            
            //JasperViewer.viewReport(jprint);
            
            JasperViewer visor=new JasperViewer(jprint,false);
            
            visor.setVisible(true);
            
          //  visor.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            
            
        } catch (JRException ex) {
            Logger.getLogger(archivoSistema.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_generarActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
      
        
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        
       
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void generar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generar1ActionPerformed
        // TODO add your handling code here:
        
         ArrayList lista=new ArrayList();
        
        for(int i=0;i<jTable2.getRowCount();i++){
            
            ListaAuditorPago misArticulos=new ListaAuditorPago(jTable2.getValueAt(i, 6).toString(),jTable2.getValueAt(i, 7).toString(),jTable2.getValueAt(i, 8).toString(),jTable2.getValueAt(i, 9).toString());
            
            lista.add(misArticulos);
            
        }
        
        try {
            File fichero = new File("src/Reporte/ReporteAuditorPago.jasper");
            String ruta=fichero.getAbsolutePath();
            String barra=File.separator;
            String dobleBarra=File.separator+File.separator;
            String rutaNueva=ruta.replace(barra,dobleBarra);
                                                                          
            JasperReport reporte=(JasperReport) JRLoader.loadObjectFromFile(rutaNueva);
            
            Map parametro = new HashMap();
            parametro.put("auditor", ventana_supervisor.jTextField1.getText());
            parametro.put("desde", jComboBox3.getSelectedItem());
            parametro.put("hasta", jComboBox4.getSelectedItem());
            
            JasperPrint jprint=JasperFillManager.fillReport(reporte,parametro,new JRBeanCollectionDataSource(lista));
            
            //JasperViewer.viewReport(jprint);
            
            JasperViewer visor=new JasperViewer(jprint,false);
            
            visor.setVisible(true);
            
          //  visor.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            
            
        } catch (JRException ex) {
            Logger.getLogger(archivoSistema.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_generar1ActionPerformed

    public class itemSeleccionado implements ItemListener{
       
        @Override
        public void itemStateChanged(ItemEvent e) {
            
             if (e.getStateChange() == ItemEvent.SELECTED) {
                    // Aqui es donde se escribe el manejador del event        
                 try {
                     String desde=jComboBox1.getSelectedItem().toString();
                     
                     if(desde=="Todos"){
                         
                          mod=metodos.dameModelo("auditorArticulo");
        
                          jTable1.setModel(mod);
                         
                     }else{
                         
                     DefaultTableModel md=(DefaultTableModel)jTable1.getModel();
        
                     jTable1.setModel(md);
                     
                     SimpleDateFormat formato=new SimpleDateFormat("yyyy-MM-dd");
                     
                     Date date1=formato.parse(desde); 
                     
                     int i=0;
                     int tope=jTable1.getRowCount();
                     while(i<tope){
                         
                       String comparar=jTable1.getValueAt(i, 3).toString();
                    
                       Date date2=formato.parse(comparar);
                     
                       if(date2.before(date1)){
                         //JOptionPane.showMessageDialog(null, "esta despues");
                         md.removeRow(i);
                         tope=tope-1;
                       }else{
                           i++;
                       }
                         
                     }
                     }
                     
                 } catch (ParseException ex) {
                     Logger.getLogger(registrosAuditoria.class.getName()).log(Level.SEVERE, null, ex);
                 }
                 
             }
           
        }

     
    
    }
    
    public class itemHasta implements ItemListener{
       
        @Override
        public void itemStateChanged(ItemEvent e) {
            
             if (e.getStateChange() == ItemEvent.SELECTED) {
                    // Aqui es donde se escribe el manejador del event        
                 try {
                     String hasta=jComboBox2.getSelectedItem().toString();
                     
                     if(hasta=="Todos"){
                         
                          mod=metodos.dameModelo("auditorArticulo");
        
                          jTable1.setModel(mod);
                         
                     }else{
                         
                     DefaultTableModel md=(DefaultTableModel)jTable1.getModel();
        
                     jTable1.setModel(md);
                     
                     SimpleDateFormat formato=new SimpleDateFormat("yyyy-MM-dd");
                     
                     Date date1=formato.parse(hasta); 
                     
                     int i=0;
                     int tope=jTable1.getRowCount();
                     while(i<tope){
                         
                       String comparar=jTable1.getValueAt(i, 3).toString();
                    
                       Date date2=formato.parse(comparar);
                     
                       if(date2.after(date1)){
                         //JOptionPane.showMessageDialog(null, "esta despues");
                         md.removeRow(i);
                         tope=tope-1;
                       }else{
                           i++;
                       }
                         
                     }
                     }
                     
                 } catch (ParseException ex) {
                     Logger.getLogger(registrosAuditoria.class.getName()).log(Level.SEVERE, null, ex);
                 }
                 
             }
           
        }

     
    
    }
    
     public class itemPago1 implements ItemListener{
       
        @Override
        public void itemStateChanged(ItemEvent e) {
            
             if (e.getStateChange() == ItemEvent.SELECTED) {
                    // Aqui es donde se escribe el manejador del event        
                 try {
                     String hasta=jComboBox3.getSelectedItem().toString();
                     
                     if(hasta=="Todos"){
                         
                          mod2=metodos.dameModelo("auditorPago");
        
                          jTable2.setModel(mod2);
                         
                     }else{
                         
                     DefaultTableModel md=(DefaultTableModel)jTable2.getModel();
        
                     jTable2.setModel(md);
                     
                     SimpleDateFormat formato=new SimpleDateFormat("yyyy-MM-dd");
                     
                     Date date1=formato.parse(hasta); 
                     
                     int i=0;
                     int tope=jTable2.getRowCount();
                     while(i<tope){
                         
                       String comparar=jTable2.getValueAt(i, 3).toString();
                    
                       Date date2=formato.parse(comparar);
                     
                       if(date2.before(date1)){
                         //JOptionPane.showMessageDialog(null, "esta despues");
                         md.removeRow(i);
                         tope=tope-1;
                       }else{
                           i++;
                       }
                         
                     }
                     }
                     
                 } catch (ParseException ex) {
                     Logger.getLogger(registrosAuditoria.class.getName()).log(Level.SEVERE, null, ex);
                 }
                 
             }
           
        }
    }
     
    public class itemPago2 implements ItemListener{
       
        @Override
        public void itemStateChanged(ItemEvent e) {
            
             if (e.getStateChange() == ItemEvent.SELECTED) {
                    // Aqui es donde se escribe el manejador del event        
                 try {
                     String hasta=jComboBox4.getSelectedItem().toString();
                     
                     if(hasta=="Todos"){
                         
                          mod2=metodos.dameModelo("auditorPago");
        
                          jTable2.setModel(mod2);
                         
                     }else{
                         
                     DefaultTableModel md=(DefaultTableModel)jTable2.getModel();
        
                     jTable2.setModel(md);
                     
                     SimpleDateFormat formato=new SimpleDateFormat("yyyy-MM-dd");
                     
                     Date date1=formato.parse(hasta); 
                     
                     int i=0;
                     int tope=jTable2.getRowCount();
                     while(i<tope){
                         
                       String comparar=jTable2.getValueAt(i, 3).toString();
                    
                       Date date2=formato.parse(comparar);
                     
                       if(date2.after(date1)){
                         //JOptionPane.showMessageDialog(null, "esta despues");
                         md.removeRow(i);
                         tope=tope-1;
                       }else{
                           i++;
                       }
                         
                     }
                     }
                     
                 } catch (ParseException ex) {
                     Logger.getLogger(registrosAuditoria.class.getName()).log(Level.SEVERE, null, ex);
                 }
                 
             }
           
        }
    }

    
    public String anterior,siguiente,anterior2,siguiente2;
    public TableRowSorter trs,filtro1;
    public metodosTabla metodos;
    public DefaultTableModel mod,mod2;
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton generar;
    private javax.swing.JButton generar1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}

