/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Administracion;

import Login.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author jonathan
 */
public class registros extends javax.swing.JPanel {

    /**
     * Creates new form registros
     */
    DefaultTableModel tablamodel;
    public registros() {
        initComponents();
        
        misMetodos=new metodosTabla();
        
        mod=misMetodos.dameModelo("usuarios");
        
        jTable2.setModel(mod);
        
        crearSelect();
          
        tablamodel=new DefaultTableModel(null, getColumnas());
        setfilas();
        jTable1.setModel(tablamodel);
        
         jLabel9.setVisible(false);
         jLabel8.setVisible(false);
         jLabel5.setVisible(false);
         jLabel7.setVisible(false);
    }

    
    
    private String[] getColumnas(){
    String columna[]= new String[]{"Id_perfil","Descripcion"};
    return columna;
}
    
    private void setfilas(){
    
       try{
           coneccionBD connn=new coneccionBD();
       
           ResultSet res=connn.listar("perfiles");
           Object datos[]=new Object[2];
       while (res.next()) {
           
           for (int i=0;i<2;i++){
               datos[i]=res.getObject(i+1);
           }
                 /*   System.out.println(""+res.getInt("idproducto")+"       "+res.getString("prod_descripcion"));
                   String nombre= res.getString("prod_descripcion");
                   int idd =res.getInt("idproducto");*/
                   
                   
                    tablamodel.addRow(datos);
                }
       }catch(SQLException e){
           System.out.println("fallo");
	   e.printStackTrace();
       }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jPanel6 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));

        jTabbedPane1.setBackground(new java.awt.Color(204, 204, 204));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("Modificar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("Baja");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Ingresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Contraseña");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Nombre del Usuario");

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Perfil del Usuario");

        jLabel5.setText("Modificando Usuario ");

        jLabel7.setText("2");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 19, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addGap(19, 19, 19))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel4))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jButton1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(7, 7, 7))
        );

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jButton2)
                        .addGap(27, 27, 27)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(137, 137, 137))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton2))))
                .addContainerGap(253, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Usuarios", jPanel1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel3.setText("Nombre Perfil");

        jLabel6.setText("Permisos");

        jButton5.setText("Ingresar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jCheckBox4.setText("Alta Formas Pago");

        jCheckBox5.setText("Baja Formas Pago");

        jCheckBox3.setText("Modificacion Formas pago");

        jCheckBox9.setText("Consulta Formas pago");

        jCheckBox10.setText("Listado Formas pago");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox3)
                    .addComponent(jCheckBox9)
                    .addComponent(jCheckBox10, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBox4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jCheckBox1.setText("Alta Articulos");

        jCheckBox2.setText("Baja Articulos");

        jCheckBox6.setText("Modificacion Articulos");

        jCheckBox7.setText("Consulta Articulos");

        jCheckBox8.setText("Listado Articulos");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox8, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox7)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jCheckBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCheckBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox8))
        );

        jLabel8.setText("Modificando Perfil");

        jLabel9.setText("7");

        jButton4.setText("Modificar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton6.setText("Eliminar");
        jButton6.setToolTipText("");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel8)
                        .addGap(62, 62, 62)
                        .addComponent(jLabel9))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jButton5)
                        .addGap(28, 28, 28)
                        .addComponent(jButton4)
                        .addGap(30, 30, 30)
                        .addComponent(jButton6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton4)
                    .addComponent(jButton6))
                .addGap(100, 100, 100))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(128, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(243, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Perfiles", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 904, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Usuarios");
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        String usuario=jTextField2.getText();
        String pass=jTextField4.getText();
        if ( ! usuario.equals("") && ! pass.equals("")){
            perfiles perfiles=(perfiles) jComboBox1.getSelectedItem();
            int id = perfiles.getId();
            try{
                coneccionBD connn=new coneccionBD();
                String tabla="usuarios";
                String campos="usu_nombre,usu_pass,usu_perfil";
                String valores="'"+usuario+"' , '"+pass+"' ,"+String.valueOf(id);

                Boolean res1=connn.insertar(tabla,campos,valores);

                JOptionPane.showMessageDialog(null, "Usuario "+usuario+" insertado!");
                jTextField2.setText(null);
                jTextField4.setText(null);
                limpiartabla(mod);
                mod=misMetodos.dameModelo("usuarios");
                jTable2.setModel(mod);
            }catch(Exception e){
                System.out.println("fallo");
                e.printStackTrace();
            }
        }else{
            JOptionPane.showMessageDialog(null, "Complete todos los campos!");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String id_usu=jLabel7.getText();
        String nombre_usu=jTextField2.getText();
        String usu_contra=jTextField4.getText();
        perfiles perfiles=(perfiles) jComboBox1.getSelectedItem();
            
        int id_perfil=perfiles.getId();
        if(! id_usu.equals("") && !nombre_usu.equals("") && !usu_contra.equals("")){
             try{
                coneccionBD connn=new coneccionBD();
                String tabla="usuarios";
                String valor1="usu_nombre= '"+nombre_usu+"' , usu_contra ='"+usu_contra+"' , usu_perfil= "+id_perfil;
                String campoid="usu_clave";
                Boolean res1=connn.actualizaRegistro(valor1, id_usu ,  tabla, campoid);
                    if (res1){
                        JOptionPane.showMessageDialog(null, "Usuario "+id_usu+" modificado!");
                    }
                
                jTextField2.setText(null);
                jTextField4.setText(null);
                limpiartabla(mod);
                mod=misMetodos.dameModelo("usuarios");
                jTable2.setModel(mod);
            }catch(Exception e){
                System.out.println("fallo");
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String nombre=jTextField1.getText();
        if (!nombre.equals("")){
            try{
               coneccionBD connn=new coneccionBD();
                String tabla="perfiles";
                String campos="descripcion";
                String valores="'"+nombre+"'";

                int id_perfil=connn.insertar2(tabla,campos,valores);
               // System.out.println(id_perfil);
                int altaart=0;
                if (jCheckBox1.isSelected()){
                  altaart=1;  
                }
                int bajaart=0;
                if (jCheckBox2.isSelected()){
                  bajaart=1;  
                }
                int modart=0;
                if (jCheckBox6.isSelected()){
                  modart=1;  
                }
                int consart=0;
                if (jCheckBox7.isSelected()){
                  consart=1;  
                }
                int listadoart=0;
                if (jCheckBox8.isSelected()){
                  listadoart=1;  
                }
                String tabla2="permisos";
                String campos2="id_modulo, alta, baja, modif, id_perfil, consulta, listado";
                String valores2="1, "+String.valueOf(altaart)+", "+String.valueOf(bajaart)+", "+String.valueOf(modart)+ ", "+String.valueOf(id_perfil)+", "+String.valueOf(consart)+", "+ String.valueOf(listadoart);
                boolean ress1=connn.insertar(tabla2,campos2,valores2);
                
                //INSERTO EL OTRO MODULO
                int altapago=0;
                if (jCheckBox4.isSelected()){
                  altapago=1;  
                }
                int bajapago=0;
                if (jCheckBox5.isSelected()){
                  bajapago=1;  
                }
                int modpago=0;
                if (jCheckBox3.isSelected()){
                  modpago=1;  
                }
                int conspago=0;
                if (jCheckBox9.isSelected()){
                  conspago=1;  
                }
                int listadopago=0;
                if (jCheckBox10.isSelected()){
                  listadopago=1;  
                }
                String valores3="2, "+String.valueOf(altapago)+", "+String.valueOf(bajapago)+", "+String.valueOf(modpago)+ ", "+String.valueOf(id_perfil)+", "+String.valueOf(conspago)+", "+ String.valueOf(listadopago);
                boolean ress2=connn.insertar(tabla2,campos2,valores3);
                if (ress1 && ress2){
                    JOptionPane.showMessageDialog(null, "Perfil "+nombre+" insertado!"); 
                    crearSelect();
                }
                
                jTextField1.setText(null);
                limpiartabla(tablamodel);
                tablamodel=new DefaultTableModel(null, getColumnas());
                setfilas();
                jTable1.setModel(tablamodel);
                
                
            }catch(Exception e){
                
            }
        }else{
            JOptionPane.showMessageDialog(null, "Complete todos los campos!");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       
        if ( jTable2.getSelectedRow()!= -1){
           try{
                coneccionBD connn=new coneccionBD();
                int fila=jTable2.getSelectedRow();
                 //System.out.println("fila "+String.valueOf(fila));

               String idd=jTable2.getValueAt(fila, 0).toString();
               //System.out.println(idd);
                String tabla="usuarios";
                String campoid="usu_clave";
                boolean ress=connn.eliminaRegistro(tabla,idd,campoid);
                if (ress==true){
                    JOptionPane.showMessageDialog(null, "Cliente "+idd+" eliminado!");

                    limpiartabla(mod);
                    
                  mod=misMetodos.dameModelo("usuarios");
        
                    jTable2.setModel(mod);
                }else{
                    JOptionPane.showMessageDialog(null, "No se elimino el usuario "+idd); 
                }
                }catch(Exception e){
                     System.out.println("fallo");
                    e.printStackTrace();
                }
       }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        if ( jTable2.getSelectedRow()!= -1){
                 int fila=jTable2.getSelectedRow();
                    
                 String idd=jTable2.getValueAt(fila, 3).toString();
               //  System.out.println(idd);
                 try{
                     coneccionBD connn=new coneccionBD();
                     ResultSet resultado= connn.registroTabla("perfiles","id_perfil", Integer.valueOf(idd));
                     String nombr;
                     if (resultado.next()){
                         nombr=resultado.getString("descripcion");
                        //  System.out.println(nombr);
                         seleccionarPerfil(nombr, jComboBox1);
                     }
                    
                 }catch(Exception e){
                      e.printStackTrace();
                 }
                
                 //setSelectedValue(jComboBox1,"Auditor");
                 String nombre =jTable2.getValueAt(fila, 1).toString();
                 jTextField2.setText(nombre);
                 String pass =jTable2.getValueAt(fila, 2).toString();
                 jTextField4.setText(pass);
                 String id_user=jTable2.getValueAt(fila, 0).toString();
                 jLabel7.setText(id_user);
                 jLabel5.setVisible(true);
                 jLabel7.setVisible(true);
        }
    }//GEN-LAST:event_jTable2MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        
        if ( jTable1.getSelectedRow()!= -1){
                 int fila=jTable1.getSelectedRow();
                    
                 String idd=jTable1.getValueAt(fila, 0).toString();
               //  System.out.println(idd);
                 try{
                     coneccionBD connn=new coneccionBD();
                     String tabla="permisos";
                     String filtro="where id_perfil= "+idd+" and id_modulo=1";
                     ResultSet resultado= connn.registroTablaconFiltro( tabla, filtro);
                     
                     if (resultado.next()){
                         int alta_pago=resultado.getByte("alta");
                         int baja_pago=resultado.getByte("baja");
                         int mod_pago=resultado.getByte("modif");
                         int cons_pago=resultado.getByte("consulta");
                         int listado_pago=resultado.getByte("listado");
                         if(alta_pago==1){
                             jCheckBox4.setSelected(true);
                         }else{
                            jCheckBox4.setSelected(false); 
                         }
                         if(baja_pago==1){
                             jCheckBox5.setSelected(true);
                         }else{
                            jCheckBox5.setSelected(false); 
                         }
                          if(mod_pago==1){
                             jCheckBox3.setSelected(true);
                         }else{
                            jCheckBox3.setSelected(false); 
                         }
                          if(cons_pago==1){
                             jCheckBox9.setSelected(true);
                         }else{
                            jCheckBox9.setSelected(false); 
                         }
                          if(listado_pago==1){
                             jCheckBox10.setSelected(true);
                         }else{
                            jCheckBox10.setSelected(false); 
                         }
                     }else{
                         jCheckBox4.setSelected(false); 
                         jCheckBox5.setSelected(false);
                         jCheckBox3.setSelected(false);
                         jCheckBox9.setSelected(false);
                         jCheckBox10.setSelected(false);
                     }
                    String filtro2="where id_perfil= "+idd+" and id_modulo=2";
                     ResultSet resultado2= connn.registroTablaconFiltro( tabla, filtro2);
                     
                     if (resultado2.next()){ 
                         int alta_stock=resultado2.getByte("alta");
                         int baja_stock=resultado2.getByte("baja");
                         int mod_stock=resultado2.getByte("modif");
                         int cons_stock=resultado2.getByte("consulta");
                         int listado_stock=resultado2.getByte("listado");
                         //System.out.println(alta_stock+" "+baja_stock+" "+mod_stock+" "+cons_stock+" "+listado_stock);
                         if(alta_stock==1){
                             jCheckBox1.setSelected(true);
                         }else{
                            jCheckBox1.setSelected(false); 
                         }
                         if(baja_stock==1){
                             jCheckBox2.setSelected(true);
                         }else{
                            jCheckBox2.setSelected(false); 
                         }
                          if(mod_stock==1){
                             jCheckBox6.setSelected(true);
                         }else{
                            jCheckBox6.setSelected(false); 
                         }
                          if(cons_stock==1){
                             jCheckBox7.setSelected(true);
                         }else{
                            jCheckBox7.setSelected(false); 
                         }
                          if(listado_stock==1){
                             jCheckBox8.setSelected(true);
                         }else{
                            jCheckBox8.setSelected(false); 
                         }
                     }else{
                         jCheckBox1.setSelected(false); 
                         jCheckBox2.setSelected(false);
                         jCheckBox6.setSelected(false);
                         jCheckBox7.setSelected(false);
                         jCheckBox8.setSelected(false);
                     }
                 }catch(Exception e){
                      e.printStackTrace();
                 }
                
                 String nombre_perfil =jTable1.getValueAt(fila, 1).toString();
                 jTextField1.setText(nombre_perfil);
                 jLabel9.setText(idd);
                 jLabel9.setVisible(true);
                 jLabel8.setVisible(true);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String id_perfil=jLabel9.getText();
        if(! id_perfil.equals("") && ! jTextField1.getText().equals("")){
        try{
            
                    coneccionBD connn=new coneccionBD();
                    String tabla_perf="perfiles";
                    String nombre_perf=jTextField1.getText();
                    String valor0=" descripcion = '"+nombre_perf+"'"; 
                    String campoid0="id_perfil";
                    boolean res0= connn.actualizaRegistro( valor0, id_perfil ,  tabla_perf, campoid0);
                    String tabla="permisos";
                    String filtro="where id_perfil= "+jLabel9.getText();
                    ResultSet permisos=connn.registroTablaconFiltro(tabla,filtro);
                    boolean res=false;
                    int cant=0;
                     if (permisos.last()){
                    cant = permisos.getRow();
                    }
                    if (cant > 0){
                      res=true;  
                    }
                     System.out.println("cant"+cant+ " res "+res);
                     permisos.close();
                     if(res){
                         //modifico
                         int altaart=0;
                            if (jCheckBox1.isSelected()){
                              altaart=1;  
                            }
                            int bajaart=0;
                            if (jCheckBox2.isSelected()){
                              bajaart=1;  
                            }
                            int modart=0;
                            if (jCheckBox6.isSelected()){
                              modart=1;  
                            }
                            int consart=0;
                            if (jCheckBox7.isSelected()){
                              consart=1;  
                            }
                            int listadoart=0;
                            if (jCheckBox8.isSelected()){
                              listadoart=1;  
                            }
                         String ids1=id_perfil+" and id_modulo=1";
                         String campoid="id_perfil";
                         String valor="alta= "+altaart+", baja= "+bajaart+", modif= "+modart+", consulta= "+consart+", listado= "+listadoart;
                         
                        boolean res1= connn.actualizaRegistro( valor, ids1 ,  tabla, campoid);
                        
                        int altapago=0;
                            if (jCheckBox4.isSelected()){
                              altapago=1;  
                            }
                            int bajapago=0;
                            if (jCheckBox5.isSelected()){
                              bajapago=1;  
                            }
                            int modpago=0;
                            if (jCheckBox3.isSelected()){
                              modpago=1;  
                            }
                            int conspago=0;
                            if (jCheckBox9.isSelected()){
                              conspago=1;  
                            }
                            int listadopago=0;
                            if (jCheckBox10.isSelected()){
                              listadopago=1;  
                            }
                        
                        String ids2=id_perfil+" and id_modulo=2";
                         String valor2="alta= "+altapago+", baja= "+bajapago+", modif= "+modpago+", consulta= "+conspago+", listado= "+listadopago;
                         
                        boolean res2= connn.actualizaRegistro( valor2, ids2 ,  tabla, campoid);
                         if (res1 && res2){
                                JOptionPane.showMessageDialog(null, "Perfil "+id_perfil+" modificado!"); 
                                crearSelect();
                            }
                     }else{
                            //inserto
                            int altaart=0;
                            if (jCheckBox1.isSelected()){
                              altaart=1;  
                            }
                            int bajaart=0;
                            if (jCheckBox2.isSelected()){
                              bajaart=1;  
                            }
                            int modart=0;
                            if (jCheckBox6.isSelected()){
                              modart=1;  
                            }
                            int consart=0;
                            if (jCheckBox7.isSelected()){
                              consart=1;  
                            }
                            int listadoart=0;
                            if (jCheckBox8.isSelected()){
                              listadoart=1;  
                            }
                            String tabla2="permisos";
                            String campos2="id_modulo, alta, baja, modif, id_perfil, consulta, listado";
                            String valores2="1, "+String.valueOf(altaart)+", "+String.valueOf(bajaart)+", "+String.valueOf(modart)+ ", "+String.valueOf(id_perfil)+", "+String.valueOf(consart)+", "+ String.valueOf(listadoart);
                            boolean ress1=connn.insertar(tabla2,campos2,valores2);

                            //INSERTO EL OTRO MODULO
                            int altapago=0;
                            if (jCheckBox4.isSelected()){
                              altapago=1;  
                            }
                            int bajapago=0;
                            if (jCheckBox5.isSelected()){
                              bajapago=1;  
                            }
                            int modpago=0;
                            if (jCheckBox3.isSelected()){
                              modpago=1;  
                            }
                            int conspago=0;
                            if (jCheckBox9.isSelected()){
                              conspago=1;  
                            }
                            int listadopago=0;
                            if (jCheckBox10.isSelected()){
                              listadopago=1;  
                            }
                            String valores3="2, "+String.valueOf(altapago)+", "+String.valueOf(bajapago)+", "+String.valueOf(modpago)+ ", "+String.valueOf(id_perfil)+", "+String.valueOf(conspago)+", "+ String.valueOf(listadopago);
                            boolean ress2=connn.insertar(tabla2,campos2,valores3);
                            if (ress1 && ress2){
                                
                                JOptionPane.showMessageDialog(null, "Perfil "+id_perfil+" modificado!"); 
                                crearSelect();
                                
                            }
                     }
                        
                                limpiartabla(tablamodel);
                                tablamodel=new DefaultTableModel(null, getColumnas());
                                setfilas();
                                jTable1.setModel(tablamodel);
                    

                }catch(Exception e){
                    System.out.println("fallo");
                    e.printStackTrace();
                }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       String id_perfil=jLabel9.getText();
       if(! id_perfil.equals("")){
            try{
              coneccionBD con=new coneccionBD();
               boolean resultado=con.elimina_perfil(id_perfil);
               if(resultado){
                    JOptionPane.showMessageDialog(null, "Perfil "+id_perfil+" eliminado!"); 
                    limpiartabla(tablamodel);
                tablamodel=new DefaultTableModel(null, getColumnas());
                setfilas();
                jTable1.setModel(tablamodel);
               }else{
                    JOptionPane.showMessageDialog(null, "No se elimino perfil "+id_perfil+", es usado por uno o mas usuarios!"); 
               }
           }catch(Exception e){
               e.printStackTrace();
           }
       }
    }//GEN-LAST:event_jButton6ActionPerformed
 private static void seleccionarPerfil(String s, JComboBox combo) {
    for (int i=0; i<combo.getItemCount(); i++) {
      if (combo.getItemAt(i).toString().equals(s)) {
        combo.setSelectedIndex(i);
        break;
      }
    }
    return;
  }
    private void crearSelect(){
        DefaultComboBoxModel value=null;
        try{
                    coneccionBD connn=new coneccionBD();
                    String tabla="perfiles";
                    ResultSet perfil=connn.listar(tabla);
                    value =new DefaultComboBoxModel();
                      jComboBox1.setModel(value);
                     while (perfil.next()) {         
                       value.addElement(new perfiles(perfil.getString("descripcion"),perfil.getInt("id_perfil")));
                     }
                     
                     perfil.close();
                    
                    

                }catch(Exception e){
                    System.out.println("fallo");
                    e.printStackTrace();
                }
        
    }
    
    private void limpiartabla(DefaultTableModel modelo){
    while(modelo.getRowCount()>0)modelo.removeRow(0);
    }

    private metodosTabla misMetodos;
     public DefaultTableModel mod,mod2;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
