/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Contabilidad;

import static Contabilidad.menues.jDesktopPane1;
import java.sql.*;
import javax.swing.JInternalFrame;
import Login.*;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author jonathan
 */
public class diarioMayor extends javax.swing.JInternalFrame {

    /**
     * Creates new form diarioMayor
     */
    public diarioMayor() {
        initComponents();
        
        setSize(1339,652);
        
        bd=new coneccionBD();
          cabecera=new String[7];
            
          cabecera[0]="Nro Asiento";
          cabecera[1]="Fecha Contable";
          cabecera[2]="Tipo de Asiento";
          cabecera[3]="OK Carga";
          cabecera[4]="Registrao";
          cabecera[5]="Fecha de Cierre";
          cabecera[6]="Fecha de Apertura";
          
       String consulta="SELECT nro_asiento,DATE_FORMAT(fecha_contable, '%d-%m-%Y')as fecha_contable,tipo_as,ok_carga,registrado,DATE_FORMAT(fecha_cierre, '%d-%m-%Y')as fecha_cierre,DATE_FORMAT(fecha_apertura, '%d-%m-%Y')as fecha_apertura FROM diario_mayor GROUP BY nro_asiento";  
       dat=dameMatriz1(consulta);
       DefaultTableModel modelo=new DefaultTableModel(dat,cabecera);
       jTable3.setModel(modelo);
       
          cabecera2=new String[10];
            
          cabecera2[0]="Nro Asiento";
          cabecera2[1]="Nro Renglon";
          cabecera2[2]="Nro Cuenta";
          cabecera2[3]="Descripcion";
          cabecera2[4]="Comprobante";
          cabecera2[5]="Sucursal";
          cabecera2[6]="Seccion";
          cabecera2[7]="Debe/Haber";
          cabecera2[8]="Importe";
          cabecera2[9]="Leyenda";
          
       String consulta2="select nro_asiento,nro_renglon,nro_cuenta,descripcion,comprobante,sucursal,seccion,debe_haber,importe,leyenda from diario_mayor order by nro_asiento";  
       dat2=dameMatriz1(consulta2);
       DefaultTableModel modelo2=new DefaultTableModel(dat2,cabecera2);
      // jTable1.setModel(modelo2);
       
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/book.png"))); // NOI18N
        jButton1.setText("Libro Mayor");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setIconTextGap(3);
        jButton1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/newspaper.png"))); // NOI18N
        jButton2.setText("Libro Diario");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setIconTextGap(3);
        jButton2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/balance.png"))); // NOI18N
        jButton3.setText("Balance");
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setIconTextGap(3);
        jButton3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTable3 = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int ColIndex){
                return false;
            }
        };
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable3.getTableHeader().setResizingAllowed(false);
        jTable3.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jTable3);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(457, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        carga_balance_auxiliar();
        fechBalance na=new fechBalance();
        menues.jDesktopPane1.add(na);
        
        na.toFront();
        na.setVisible(true);
        centrar(na);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
         datMayor na=new datMayor();
        menues.jDesktopPane1.add(na);
        
        na.toFront();
        na.setVisible(true);
        centrar(na);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Diario na=new Diario();
        menues.jDesktopPane1.add(na);
        
        na.toFront();
        na.setVisible(true);
        centrar(na);
    }//GEN-LAST:event_jButton2ActionPerformed

       public void centrar (JInternalFrame interno){
        
        int x=(jDesktopPane1.getWidth()/2 - interno.getWidth()/2);
        int y=(jDesktopPane1.getHeight()/2 - interno.getHeight()/2);
        
        if(interno.isShowing()){
            interno.setLocation(x, y);
        }else{
            jDesktopPane1.add(interno);
            interno.setLocation(x, y);
            interno.show();
        }
    }
       
     private String[][] dameMatriz1(String sql){
       Statement miSentencia=bd.dameSentencia(); 
        String [][]datos = null;
        try{
            ResultSet rs=miSentencia.executeQuery(sql);
            
            rs.last();
	        	 
	    ResultSetMetaData rsmd = rs.getMetaData();
	      
	    int numCols = rsmd.getColumnCount();
	      
	    int numFils =rs.getRow();
	      
	    datos =new String[numFils][numCols];
	            
	    int i=0;
	            
	    rs.beforeFirst();
	        	
	    while(rs.next()){	
	        for(int j=0;j<numCols;j++){
	        			
	          datos[i][j]=rs.getString(j+1);	
	        			
	        }
	     i++;
	    }
          
            
        }catch(Exception e){
            
        }
        return datos;
    }
     
     private void carga_balance_auxiliar(){
        String vacia="TRUNCATE balanza_auxuliar";
        Statement bal=bd.dameSentencia();
        
        ResultSet rt=bd.listar("plan_cuentas");
        try{
            bal.executeUpdate(vacia);
            while(rt.next()){
                 insertabalance="insert into balanza_auxuliar values('"+rt.getString("nro_cuenta")+"','"+rt.getString("codigo_cta")+"','"+rt.getString("descripcion")+"','"+rt.getString("nivel")+"','0','0','0','0','0')"; 
                 statebalance=bd.dameSentencia();
                 statebalance.executeUpdate(insertabalance);
                 statebalance.close();
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private Statement statebalance;
    private String insertabalance;
    private coneccionBD bd;
    private String [] cabecera,cabecera2;
    private String[][]dat,dat2;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    public static javax.swing.JTable jTable3;
    // End of variables declaration//GEN-END:variables
}


