/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Contabilidad;

import Login.coneccionBD;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jonathan
 */
public class Listame_ctas extends javax.swing.JInternalFrame {

    /**
     * Creates new form Listame_ctas
     */
    public Listame_ctas() {
        initComponents();
        bd=new coneccionBD();
        jTable1.setModel(dameModelo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setClosable(true);

        jTable1 = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int ColIndex){
                return false;
            }
        };
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.getTableHeader().setResizingAllowed(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        misAsientos.jTextField2.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString());
        misAsientos.jTextField3.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
        misAsientos.jTextField4.requestFocus();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    
    public String[][] dameMatriz(ResultSet rs){
		
	       String datos[][] = null;
			
	        try{
	        	
	             rs.last();
	        	 
	             ResultSetMetaData rsmd = rs.getMetaData();
	      
	             int numCols = rsmd.getColumnCount();
	      
	             int numFils =rs.getRow();
	      
	            datos =new String[numFils][numCols];
	            
	            int i=0;
	            
	            rs.beforeFirst();
	        	
	        	while(rs.next()){	
	        		for(int j=0;j<numCols;j++){
	        			
	        			datos[i][j]=rs.getString(j+1);	
	        			
	        		}
	        		i++;
	        	}
	        
				
			}catch(Exception e){
				
				System.out.println("no conecta");
				e.printStackTrace();
				
			}
	        		
			return datos;
			
			
     }
    
    public DefaultTableModel dameModelo(){
        
       coneccionBD miConexion=new coneccionBD();
          
            cabecera=new String[5];
            
            cabecera[0]="Codigo de Cuenta";
            cabecera[1]="Descripcion";
            cabecera[2]="nro_cuenta";
            cabecera[3]="Nivel";
            cabecera[4]="Imputa";
            
            
         //   ResultSet dat2=miConexion.listar("plan_cuentas");
            String sql="select * from plan_cuentas where imputa='1'";
            Statement st=bd.dameSentencia();
            try{
               ResultSet dat2=st.executeQuery(sql);
               datos=dameMatriz(dat2);
            }catch(Exception e){}
            
          
      
        DefaultTableModel modelo=new DefaultTableModel(datos,cabecera);
        
        return modelo;
        
    }
    
    private coneccionBD bd;
    private String[] cabecera;
    private String[][] datos;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
