/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Contabilidad;

import static Contabilidad.menues.jDesktopPane1;
import Login.coneccionBD;
import java.awt.event.*;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.*;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Locale;
import java.text.SimpleDateFormat;
import java.util.Date;
import Reporte.*;
import java.awt.KeyboardFocusManager;
import java.io.*;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Map;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

public class misAsientos extends javax.swing.JInternalFrame {

    /**
     * Creates new form misAsientos
     */
    public misAsientos() {
        initComponents();
        setSize(1339,652);
        
        bd=new coneccionBD();
        
        df = new DecimalFormat("#.00");
        DecimalFormatSymbols dfs = df.getDecimalFormatSymbols();
        dfs.setDecimalSeparator('.');
        df.setDecimalFormatSymbols(dfs);
        
        jTextField3.setEditable(false);
        jTextField5.setEditable(false);
        jTextField1.setEditable(false);
        
        ResultSet comSuc=bd.listar("sucursales");
        try{
            while(comSuc.next()){
                jComboBox2.addItem(comSuc.getString("descripcion"));
            }
        }catch(Exception e){
            
        }
        
        ResultSet comSec=bd.listar("seccion");
        try{
            while(comSec.next()){
                jComboBox3.addItem(comSec.getString("descripcion"));
            }
        }catch(Exception e){
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jTextField5 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel34 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Control de Asientos");

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Fecha de Apertura:");

        jLabel2.setText("Fecha de Cierre:");

        jLabel3.setText("jLabel3");

        jLabel4.setText("jLabel4");

        jLabel6.setText("Razon Social");

        jLabel7.setText("jLabel7");

        jLabel8.setText("Situacion IVA");

        jLabel9.setText("jLabel9");

        jLabel10.setText("CUIT");

        jLabel11.setText("jLabel11");

        jLabel12.setText("Actividad Principal");

        jLabel13.setText("jLabel13");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton2.setText("ALTA");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Retomar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Listar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Pasar al Diario");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jButton4)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(61, 61, 61)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel14.setText("Fecha Contable");

        jLabel16.setText("Nro Asiento");

        jLabel18.setText("Tipo Asiento");

        jLabel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel20.setText("Ok Carga");

        jLabel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel22.setText("Registrado");

        jLabel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        try {
            jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jFormattedTextField1KeyPressed(evt);
            }
        });

        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField5KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField5KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField5)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel18)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel20)
                        .addGap(53, 53, 53)
                        .addComponent(jLabel22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel18)
                    .addComponent(jLabel20)
                    .addComponent(jLabel14)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1 = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int ColIndex){
                return false;
            }
        };
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nro Renglon", "Nro Cuenta", "Descripcion", "Comprobante", "Sucursal", "Seccion", "Debe/Haber", "Importe", "Leyenda"
            }
        ));
        jTable1.getTableHeader().setResizingAllowed(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTable1KeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setText("Total debe:");

        jLabel24.setText("jLabel24");

        jLabel25.setText("Total Haber:");

        jLabel26.setText("jLabel26");

        jLabel27.setText("Diferencia:");

        jLabel28.setText("jLabel28");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28))
                .addGap(21, 21, 21))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton7.setText("Eliminar Renglon");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Modificar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton10.setText("Abandonar");

        jButton11.setText("Grabar");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jButton7)
                .addGap(18, 18, 18)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(251, 251, 251)
                .addComponent(jButton10)
                .addGap(18, 18, 18)
                .addComponent(jButton11)
                .addContainerGap(519, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                            .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel17.setText("Nro Renglon");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        jLabel29.setText("Nro Cuenta");

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel30.setText("Comprobante");

        jLabel31.setText("Sucursal");

        jLabel32.setText("Seccion");

        jLabel33.setText("Debe/Haber");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Debe", "Haber" }));

        jLabel34.setText("Importe");

        jTextField7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField7KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField7KeyTyped(evt);
            }
        });

        jButton12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton12.setText("OK");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2KeyReleased(evt);
            }
        });

        jLabel35.setText("Leyenda");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addGap(44, 44, 44)
                        .addComponent(jLabel31)
                        .addGap(65, 65, 65)
                        .addComponent(jLabel32)
                        .addGap(41, 41, 41))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel35)
                        .addGap(80, 80, 80)))
                .addComponent(jButton12)
                .addContainerGap(202, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel29)
                            .addComponent(jLabel30)
                            .addComponent(jLabel31)
                            .addComponent(jLabel32)
                            .addComponent(jLabel33)
                            .addComponent(jLabel34)
                            .addComponent(jLabel35))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:

        if(jTable1.getSelectedRow()!=-1){
            DefaultTableModel md=(DefaultTableModel)jTable1.getModel();
            int rta=JOptionPane.showConfirmDialog(null, "Estas seguro ?", "eliminar", JOptionPane.YES_NO_OPTION);
            if(rta==0){
                md.removeRow(jTable1.getSelectedRow());
                hacerSumas();
            }
        }else{
            JOptionPane.showMessageDialog(null, "Selecciona el Renglon a Eliminar");
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        
       
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
        // TODO add your handling code here:
   
        
    }//GEN-LAST:event_jTable1KeyReleased

    private void jTable1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyTyped
        // TODO add your handling code here:
        
      
        
    }//GEN-LAST:event_jTable1KeyTyped

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        // TODO add your handling code here:
        
   
        
    }//GEN-LAST:event_jTable1KeyPressed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        
      if(jTable1.getSelectedRow()!=-1){
          int fila=jTable1.getSelectedRow();
          jTextField1.setText(jTable1.getValueAt(fila, 0).toString());
          jTextField2.setText(jTable1.getValueAt(fila, 1).toString());
          jTextField3.setText(jTable1.getValueAt(fila, 2).toString());
          jTextField4.setText(jTable1.getValueAt(fila, 3).toString());
          jComboBox2.setSelectedItem(jTable1.getValueAt(fila, 4).toString());
          jComboBox3.setSelectedItem(jTable1.getValueAt(fila, 5).toString());
          jComboBox1.setSelectedItem(jTable1.getValueAt(fila, 6).toString()); 
          jTextField7.setText(jTable1.getValueAt(fila, 7).toString());
          jTextField8.setText(jTable1.getValueAt(fila, 8).toString());
          
        //   DefaultTableModel md=(DefaultTableModel)jTable1.getModel(); 
        //   md.removeRow(fila);
        //   hacerSumas();
          
      }else{
            JOptionPane.showMessageDialog(null, "Selecciona el Renglon a Modificar");
        }  
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        limpiarTabla(jTable1);
        jFormattedTextField1.requestFocus();
        jLabel21.setText("Mal");
        jLabel23.setText("No Registrado");
        maximoAs="SELECT IFNULL(MAX(nro_asiento),0)AS maximo FROM asientos";
        Statement stmax=bd.dameSentencia();
        try{
            ResultSet rtmax=stmax.executeQuery(maximoAs);
            rtmax.next();
            int valor=Integer.parseInt(rtmax.getString("maximo"));
            jTextField5.setText(String.valueOf(valor+1));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
      //  numRenglon=1;
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        
        hacerSumas();
        eliminarAsiento();
           guardarAsiento();
           JOptionPane.showMessageDialog(null, "Asiento Guardado");
           limpiarTabla(jTable1);
        
        
        
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String[] arregloRetoma=dameRetomar();
        JComboBox comboRetoma=new JComboBox(arregloRetoma);
       
        String[] options = { "OK", "Cancel" };

        String title = "Asientos";
        int selection = JOptionPane.showOptionDialog(null, comboRetoma, title,
            JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE, null,
            options, options[0]); 
        
         if (selection == 0) {
             limpiarTabla(jTable1);
             String eleccion=comboRetoma.getSelectedItem().toString();
             String consultaSQL="select nro_asiento,DATE_FORMAT(fecha_contable, '%d-%m-%Y')AS fecha_contable,tipo_asiento,ok_carga,registrado,nro_renglon,nro_cuenta,descripcion,comprobante,sucursal,seccion,debe_haber,importe,leyenda from asientos where nro_asiento='"+eleccion+"'";
             Statement con=bd.dameSentencia();
             try{
                 ResultSet result=con.executeQuery(consultaSQL);
                 result.next();
                 jTextField5.setText(result.getString("nro_asiento"));
                 jFormattedTextField1.setText(result.getString("fecha_contable")); 
                 if(result.getString("tipo_asiento").equals("1")){
                      jLabel19.setText("Apertura");
                 }else if(result.getString("tipo_asiento").equals("5")){
                      jLabel19.setText("Normal");
                 }else{
                     jLabel19.setText("Cierre");
                 }
                 if(result.getString("ok_carga").equals("0")){
                      jLabel21.setText("Mal");
                 }else{
                      jLabel21.setText("Bien");
                 }
                 if(result.getString("registrado").equals("0")){
                      jLabel23.setText("No Registrado");
                 }else if(result.getString("registrado").equals("5")){
                      jLabel23.setText("En Proceso");
                 }else{
                      jLabel23.setText("Registrado");
                 }
                 ArrayList<Object[]> data=new ArrayList<>();
                 result.beforeFirst();
                 while(result.next()){
                     Object[] rows=new Object[9];
                     for(int i=0;i<rows.length;i++){
                         switch(i){
                             case 0:rows[i]=result.getObject("nro_renglon");
                                 break;
                             case 1:rows[i]=result.getObject("nro_cuenta");
                                 break;
                             case 2:rows[i]=result.getObject("descripcion");
                                 break;
                             case 3:rows[i]=result.getObject("comprobante");
                                 break;
                             case 4:rows[i]=result.getObject("sucursal");
                                 break;
                             case 5:rows[i]=result.getObject("seccion");
                                 break;
                             case 6:if(result.getString("debe_haber").equals("0")){
                                        rows[i]="Debe";
                                    }else{
                                        rows[i]="Haber";
                                    }   
                                 break;
                             case 7:rows[i]=result.getObject("importe");
                                 break;
                             case 8:rows[i]=result.getObject("leyenda");
                                 break;
                         }
                     }
                     data.add(rows);
                 }
                 DefaultTableModel md=(DefaultTableModel)this.jTable1.getModel();
                 for(int i=0;i<data.size();i++){
                     md.addRow(data.get(i));
                 }
             
             }catch(Exception e){
                 
             }
             
             String maxi="SELECT MAX(nro_renglon) as maxi FROM asientos WHERE nro_asiento='"+eleccion+"'";
             Statement maxist=bd.dameSentencia();
             try{
                 ResultSet maxirt=maxist.executeQuery(maxi);
                 maxirt.next();
                 int renglon=Integer.parseInt(maxirt.getString("maxi"))+1;
                 jTextField1.setText(String.valueOf(renglon));
                 jTextField2.requestFocus();
             }catch(Exception e){
                 
             }
         }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        Listame_asientos na=new Listame_asientos();
        menues.jDesktopPane1.add(na);
        
        na.toFront();
        na.setVisible(true);
        centrar(na);
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
  
      pasarDiario na=new pasarDiario();
        menues.jDesktopPane1.add(na);
        
        na.toFront();
        na.setVisible(true);
        centrar(na);
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        if(buscaTabla(jTextField1.getText())==false){
           Object[] fila={jTextField1.getText(),jTextField2.getText(),jTextField3.getText(),jTextField4.getText(),jComboBox2.getSelectedItem(),jComboBox3.getSelectedItem(),jComboBox1.getSelectedItem(),jTextField7.getText(),jTextField8.getText()};
           DefaultTableModel md=(DefaultTableModel)jTable1.getModel();
           md.addRow(fila);
      
        }else{
            jTable1.setValueAt(jTextField2.getText(),numRenglon , 1);
            jTable1.setValueAt(jTextField3.getText(),numRenglon , 2);
            jTable1.setValueAt(jTextField4.getText(),numRenglon , 3);
            jTable1.setValueAt(jComboBox2.getSelectedItem(),numRenglon , 4);
            jTable1.setValueAt(jComboBox3.getSelectedItem(),numRenglon , 5);
            jTable1.setValueAt(jComboBox1.getSelectedItem(),numRenglon , 6);
            jTable1.setValueAt(jTextField7.getText(),numRenglon , 7);
            jTable1.setValueAt(jTextField8.getText(),numRenglon , 8);
        }
        
        int fila = jTable1.getRowCount();
            int ant=1;
            if(fila>0){
                for (int i = 0; i < fila; i++) {
                    if(ant<Integer.parseInt(jTable1.getValueAt(i, 0).toString())){
                       ant=Integer.parseInt(jTable1.getValueAt(i, 0).toString());
                    }
                }
                ant=ant+1;
            }
            jTextField1.setText(Integer.toString(ant));      
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField7.setText("");
            jTextField2.requestFocus();
          hacerSumas();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed

         jTextField2.setFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS,java.util.Collections.EMPTY_SET);
        if (evt.getKeyCode() == KeyEvent.VK_TAB) {
            String consult="select * from plan_cuentas where nro_cuenta='"+jTextField2.getText()+"' and imputa='1'";
             if(buscaRenglon(consult)){
                 jTextField3.setText(dameDescricion(consult,"descripcion"));
                 jTextField4.requestFocus();
             }else{
                 JOptionPane.showMessageDialog(null, "Esta clave es INCORRECTA o es una Cuenta No Imputable");
                 Listame_ctas na=new Listame_ctas();
                 menues.jDesktopPane1.add(na);
        
                 na.toFront();
                 na.setVisible(true);
                 centrar(na);
             }
       //      
        }
    }//GEN-LAST:event_jTextField2KeyPressed

    private void jTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyReleased
         if(evt.getKeyCode()==KeyEvent.VK_F1 || evt.getKeyCode()==KeyEvent.VK_A){      //KeyEvent.VK_F1){

            Listame_ctas na=new Listame_ctas();
            menues.jDesktopPane1.add(na);
        
            na.toFront();
            na.setVisible(true);
            centrar(na);
         }
    }//GEN-LAST:event_jTextField2KeyReleased

    private void jFormattedTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextField1KeyPressed
         jFormattedTextField1.setFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS,java.util.Collections.EMPTY_SET);
        if (evt.getKeyCode() == KeyEvent.VK_TAB) {
            
            SimpleDateFormat sd=new SimpleDateFormat("dd-MM-yyyy");
            try{
             Date dato1=sd.parse(jLabel3.getText());
             Date dato2=sd.parse(jLabel4.getText());
             Date dato3=sd.parse(jFormattedTextField1.getText());
           if(((dato1.before(dato3) || dato1.equals(dato3)) && (dato2.after(dato3) || dato2.equals(dato3)))  ){
            if(dato1.equals(dato3)){
                jLabel19.setText("Apertura");
            }else if(dato2.equals(dato3)){
                jLabel19.setText("Cierre");
            }else{
                jLabel19.setText("Normal");
            }
             jTextField5.requestFocus();
            }else{
               JOptionPane.showMessageDialog(null, "Fecha Incorrecta");
               jFormattedTextField1.setText("");
           }
            }catch(Exception e){
                
            }    
            
            int fila = jTable1.getRowCount();
            int ant=1;
            if(fila>0){
                for (int i = 0; i < fila; i++) {
                    if(ant<Integer.parseInt(jTable1.getValueAt(i, 0).toString())){
                       ant=Integer.parseInt(jTable1.getValueAt(i, 0).toString());
                    }
                }
                ant=ant+1;
            }
            jTextField1.setText(Integer.toString(ant));
            jTextField2.requestFocus();
        }
    }//GEN-LAST:event_jFormattedTextField1KeyPressed

    private void jTextField5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyPressed

        
    }//GEN-LAST:event_jTextField5KeyPressed

    private void jTextField5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyTyped
       
    }//GEN-LAST:event_jTextField5KeyTyped

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
      
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
     
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTextField7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField7KeyPressed
        // TODO add your handling code here:
        
       jTextField7.setFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS,java.util.Collections.EMPTY_SET);
        if (evt.getKeyCode() == KeyEvent.VK_TAB) {
            
            double numero=Double.parseDouble(jTextField7.getText());
            jTextField7.setText(df.format(numero));
            jTextField8.requestFocus();
        }
        
    }//GEN-LAST:event_jTextField7KeyPressed

    private void jTextField7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField7KeyTyped
       
         char caracter=evt.getKeyChar();

        if ((caracter<'0' || caracter>'9') && (caracter!='.')) {
            evt.consume();

        }
    }//GEN-LAST:event_jTextField7KeyTyped
    
    private boolean estaRenglon(String dato){
        int cantFilas=jTable1.getRowCount();
        boolean esta=false; 
        int c=0;
            do
               try{
                   if(jTable1.getValueAt(c, 0).equals(dato)){
                      esta=true;
                   }else{
                       c++;
                   }
               }catch(Exception e){
                   
               }
            while(c<cantFilas && esta==false);
       return esta;     
    }
    
    private String[] dameRetomar(){
        sql="SELECT nro_asiento FROM asientos where registrado='0' GROUP BY nro_asiento";  
        miSentencia=bd.dameSentencia();   
        try{
            ResultSet rs=miSentencia.executeQuery(sql);
            rs.last();
            int numFils =rs.getRow();
            retomar=new String[numFils];
            int i=0;
            rs.beforeFirst();
            while(rs.next()){
                
                retomar[i]=rs.getString("nro_asiento");
                i++;
                
            }
            
        }catch(Exception e){
            
        }
        return retomar;
    }
    
    private String dameDescricion(String sql, String campo){
       
        try{     
           Statement st=bd.dameSentencia();
           ResultSet r=st.executeQuery(sql);
           r.beforeFirst();
           r.next();
           descripcion=r.getString(campo);
        }catch(Exception e){
            
        }
        return descripcion;
    }
    
    private void hacerSumas(){
        
        int cantFilas=jTable1.getRowCount();
        int c=0;
        double debe=0;
        double haber=0;    
            do
                try{
                    int f=c++; 
                    String debe_haber=jTable1.getValueAt(f, 6).toString();
                    double valor=Double.parseDouble(jTable1.getValueAt(f, 7).toString());
                    
                     if(debe_haber=="Debe"){
                       debe=debe+valor;
                    }else if(debe_haber=="Haber"){
                       haber=haber+valor;
                      }
                    
                }catch(Exception e){
                    
                }
            while(c<cantFilas);
       
        jLabel24.setText(df.format(debe)); 
        jLabel26.setText(df.format(haber));
        jLabel28.setText(df.format(debe-haber));
   //   jLabel24.setText(NumberFormat.getInstance(Locale.US).format(debe));
   //   jLabel26.setText(NumberFormat.getInstance(Locale.US).format(haber));
   //   jLabel28.setText(NumberFormat.getInstance(Locale.US).format(debe-haber));
      
       if(jLabel28.getText().equals(".00")){
           jLabel21.setText("Bien");
       }else{
           jLabel21.setText("Mal");
       }
        
    }
    
    private void guardarAsiento(){
        
         try{
                miSentencia=bd.dameSentencia();
                v1=jTextField5.getText();
                v2=jFormattedTextField1.getText();
                if(jLabel19.getText().equals("Apertura")){
                    v3="1";
                }else if(jLabel19.getText().equals("Normal")){
                    v3="5";
                }else{
                    v3="9";
                }
                
                if(jLabel21.getText().equals("Mal")){
                    v4="0";
                }else{
                    v4="1";
                }
                if(jLabel23.getText().equals("No Registrado")){
                    v5="0";
                }else if(jLabel23.getText().equals("En Proceso")){
                    v5="5";
                }else{
                    v5="9";
                }
                v8=jLabel4.getText();
                v9=jLabel3.getText();    
                for(int i=0;i<jTable1.getRowCount();i++){ 
                    v6=jTable1.getValueAt(i, 0).toString();
                    v7=jTable1.getValueAt(i, 1).toString();         
                    vd=jTable1.getValueAt(i, 2).toString();
                    v10=jTable1.getValueAt(i, 3).toString();
                    v11=jTable1.getValueAt(i, 4).toString();
                    v12=jTable1.getValueAt(i, 5).toString();
                    if(jTable1.getValueAt(i, 6).toString().equals("Debe")){
                       v13="0";
                    }else{
                       v13="1"; 
                    }
                    v14=jTable1.getValueAt(i, 7).toString();
                    v15=jTable1.getValueAt(i, 8).toString();
                    sql="insert into asientos values('"+v1+"',STR_TO_DATE(REPLACE('"+v2+"','-','.') ,GET_FORMAT(date,'EUR')),"+v3+","+v4+","+v5+","+v6+",'"+v7+"','"+vd+"',STR_TO_DATE(REPLACE('"+v8+"','-','.') ,GET_FORMAT(date,'EUR')),STR_TO_DATE(REPLACE('"+v9+"','-','.') ,GET_FORMAT(date,'EUR')),'"+v10+"','"+v11+"','"+v12+"',"+v13+",'"+v14+"','"+v15+"');";
                    
                    miSentencia.executeUpdate(sql);
                    
                }
                
        }catch(Exception e){
               JOptionPane.showMessageDialog(null, e.getMessage()); 
        }
        
    }
    
    private void pasarDiarioMayor(){
        
         try{
                miSentencia=bd.dameSentencia();
                v1=jTextField5.getText();//nro asiento
                v2=jFormattedTextField1.getText();//fecha contable
                if(jLabel19.getText().equals("Apertura")){
                    v3="1";
                }else if(jLabel19.getText().equals("Normal")){
                    v3="5";
                }else{
                    v3="9";
                }
                
                if(jLabel21.getText().equals("Mal")){
                    v4="0";
                }else{
                    v4="1";
                }
                if(jLabel23.getText().equals("No Registrado")){
                    v5="0";
                }else if(jLabel23.getText().equals("En Proceso")){
                    v5="5";
                }else{
                    v5="9";
                }
                v8=jLabel4.getText();//cierre
                v9=jLabel3.getText();//apertura    
                for(int i=0;i<jTable1.getRowCount();i++){ 
                    v6=jTable1.getValueAt(i, 0).toString();//pase
                    v7=jTable1.getValueAt(i, 1).toString(); //nro cuenta
                    v16=jTable1.getValueAt(i, 2).toString();//nombre cuenta
                    v10=jTable1.getValueAt(i, 3).toString();//comrpobante
                    v11=jTable1.getValueAt(i, 4).toString();//suc
                    v12=jTable1.getValueAt(i, 5).toString();//sec
                    if(jTable1.getValueAt(i, 6).toString().equals("Debe")){
                       v13="0";
                    }else{
                       v13="1"; 
                    }
                    v14=jTable1.getValueAt(i, 7).toString();//importe
                    v15=jTable1.getValueAt(i, 8).toString();//leyenda
                    sql="insert into diario_mayor values('"+v1+"','"+v2+"',"+v3+","+v4+","+v5+","+v6+",'"+v7+"','"+v16+"','"+v8+"','"+v9+"','"+v10+"','"+v11+"','"+v12+"',"+v13+",'"+v14+"','"+v15+"');";
                    
                    miSentencia.executeUpdate(sql);
                    
                }
                
        }catch(Exception e){
               JOptionPane.showMessageDialog(null, e.getMessage()); 
        }
        
    }
    
    public void eliminarAsiento(){
        elimina_asiento="DELETE FROM asientos WHERE nro_asiento='"+jTextField5.getText()+"'";
        Statement st=bd.dameSentencia();
        try{
            st.executeUpdate(elimina_asiento);
        }catch(Exception e){
            
        }
    }
    
    public boolean buscaRenglon(String consulta){
        Statement state=bd.dameSentencia();
        boolean esta=false;
        try{
            ResultSet rFiltro=state.executeQuery(consulta);
            if(rFiltro.first()){
                esta=true;
            }
        }catch(Exception e){
            
        }
        return esta;
    }
    
    public void limpiarTabla(JTable tabla){        
        try {
            jFormattedTextField1.setText("");
            jTextField5.setText("");
            jLabel19.setText("");
            jLabel21.setText("");
            jLabel23.setText("");
            DefaultTableModel modelo=(DefaultTableModel) tabla.getModel();
            int filas=tabla.getRowCount();
            for (int i = 0;filas>i; i++) {
                modelo.removeRow(0);
            }
            jLabel24.setText("");
            jLabel26.setText("");
            jLabel28.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al limpiar la tabla.");
        }
    }
    
    public void centrar (JInternalFrame interno){
        
        int x=(jDesktopPane1.getWidth()/2 - interno.getWidth()/2);
        int y=(jDesktopPane1.getHeight()/2 - interno.getHeight()/2);
        
        if(interno.isShowing()){
            interno.setLocation(x, y);
        }else{
            jDesktopPane1.add(interno);
            interno.setLocation(x, y);
            interno.show();
        }
    }
    
    private boolean buscaTabla(String renglon){
        
        boolean esta=false;
        int f=jTable1.getRowCount();
        numRenglon=0;
        while(numRenglon<f && esta==false){
            if(jTable1.getValueAt(numRenglon, 0).equals(renglon)){
                esta=true;
            }else{
                numRenglon=numRenglon+1;
            }
        }
    return esta;
    }
    
    private Scanner lee;
    private String[]datos,dato,retomar;
    private String descripcion,elimina_asiento,consultaRenglon,consultaCuenta,consultaSucursal,maximoAs;
    private coneccionBD bd;
    private Statement miSentencia;
    private String vd,v1,v2,v3,v4,v5,v6,v7,v8,v9,v10,v11,v12,v13,v14,v15,v16,sql;
    private String n1,n2,n3,n4,n5,n6,n7,n8,n9;
    private DecimalFormat df;
    private int numRenglon;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    public static javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    public static javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    public static javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    public static javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    public static javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    public static javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    public static javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public static javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    public static javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    public static javax.swing.JTextField jTextField2;
    public static javax.swing.JTextField jTextField3;
    public static javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
